@startuml
'https://plantuml.com/state-diagram

scale 350 width


state Startside{
[*] --> Designcarport
FogKonto --> Brugeroplysninger
Menu --> BrugeInfo

Menu --> LogOut
LogOut -->[*]
Menu --> Kontakt
state Designcarport{
Designcarport --> IndtastMål : TrykPåKnappen

IndtastMål --> CarportMedFladtTag

CarportMedFladtTag --> BestilTilbud: udfyldmål
}
BestilTilbud --> TakForDinBestilling


TakForDinBestilling --> Startside : Gå tilbage til Startside




@enduml