@startuml
'https://plantuml.com/state-diagram

scale 350 width

state LogIn {
[*] --> IndtastLogin
[*] --> OpretEnBruger
}
OpretEnBruger--> SigUp
state SigUp {
IndtastOplysninger --> Opret
}

IndtastLogin --> Startside
state IndtastLogin{
LogPå:
}
SigUp --> Startside

state Startside{

state StandartCarport {
SeUdvalget:
}
state Designcarport {
IndtastMål:
}
FogKonto --> Kontooplysninger
Menu --> BrugerInfoForside
Menu --> LogOut
LogOut -->[*]
Menu --> Kontakt
}



@enduml