@startuml
'https://plantuml.com/state-diagram

scale 350 width

state LogIn {
[*] --> IndtastLogin
}

IndtastLogin --> AdminForside

state AdminForside {
 FogKonto --> Brugeroplysninger
 Logout --> [*]
 Forespørgsler :
 state Forespørgsler {
 Behandle:
 }

 Behandle --> BehandlingAfForespørgsler
 AfventerKunde : Se status
 Afsluttede : Se status

 }




@enduml