@startuml
'https://plantuml.com/state-diagram

scale 350 width
state Startside{
[*] --> BrugeInfo
Menu --> BrugeInfo
BrugeInfo --> Indbakke
Indbakke : Se Indbakke
BrugeInfo --> Forespørgsel
BrugeInfo --> KundeHistorik
KundeHistorik : Se Kundehistorikken
Forespørgsel --> StatusPåForspørgsel
StatusPåForspørgsel : Afsluttet, Afventer eller Klar
StatusPåForspørgsel --> GodkendTilbud : Hvis klar
StatusPåForspørgsel --> AfvisTilbud : Hvis klar
AfvisTilbud --> TilbudetAnnulering
GodkendTilbud --> TakForDinBestilling

Menu --> LogOut
LogOut -->[*]
Menu --> Kontakt
}
@enduml