@startuml
'https://plantuml.com/state-diagram

scale 350 width

state LogIn {
[*] --> IndtastLogin
}

IndtastLogin --> AdminForside

state AdminForside {
 FogKonto --> Brugeroplysninger
 Logout --> [*]
 Forespørgsler : Se Forespørgsler
 Forespørgsler --> DisplayForespørgsler
 DisplayForespørgsler --> BehandlingAfForespørgsler : Tryk behandle
 AfventerKunde : Se status
 Afsluttede : Se status

 }




@enduml